name: C/C++ CI

on:
  pull_request:
    branches: [ develop ]

jobs:
  build:
    env:
      NEUWARE_HOME: /usr/local/neuware
      LD_LIBRARY_PATH: "/home/jiaopu/actions-runner/_work/Paddle-Lite/Paddle-Lite/build.lite.mlu/third_party/mklml/src/extern_mklml/lib:/usr/local/neuware/lib64"

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: modity build.sh
      run: sed -i 's/DLITE_WITH_PYTHON=ON/DLITE_WITH_PYTHON=OFF/' lite/tools/build_mlu.sh && sed -i 's/WITH_TESTING=OFF/WITH_TESTING=ON/' lite/tools/build_mlu.sh && sed -i 's/PRINT_HW_TIME false/PRINT_HW_TIME true/' lite/kernels/mlu/bridges/graph.h && sed -i 's/BUILD_EXTRA=OFF/BUILD_EXTRA=ON/' lite/tools/build_mlu.sh
    - name: build
      run: ./lite/tools/build_mlu.sh build
    - name: test_act_converter_mlu
      run: ./build.lite.mlu/lite/kernels/mlu/bridges/test_act_converter_mlu
    - name: test_batch_norm_converter_mlu
      run: ./build.lite.mlu/lite/kernels/mlu/bridges/test_batch_norm_converter_mlu
    - name: test_concat_converter_mlu
      run: ./build.lite.mlu/lite/kernels/mlu/bridges/test_concat_converter_mlu
    - name: test_conv_converter_mlu
      run: ./build.lite.mlu/lite/kernels/mlu/bridges/test_conv_converter_mlu
    - name: test_dropout_converter_mlu
      run: ./build.lite.mlu/lite/kernels/mlu/bridges/test_dropout_converter_mlu
    - name: test_elementwise_converter_mlu
      run: ./build.lite.mlu/lite/kernels/mlu/bridges/test_elementwise_converter_mlu
    - name: test_fc_converter_mlu
      run: ./build.lite.mlu/lite/kernels/mlu/bridges/test_fc_converter_mlu
    - name: test_interp_converter_mlu
      run: ./build.lite.mlu/lite/kernels/mlu/bridges/test_interp_converter_mlu
    - name: test_pool_converter_mlu
      run: ./build.lite.mlu/lite/kernels/mlu/bridges/test_pool_converter_mlu
    - name: test_scale_converter_mlu
      run: ./build.lite.mlu/lite/kernels/mlu/bridges/test_scale_converter_mlu
    - name: test_softmax_converter_mlu
      run: ./build.lite.mlu/lite/kernels/mlu/bridges/test_softmax_converter_mlu
    - name: test_transpose_converter_mlu
      run: ./build.lite.mlu/lite/kernels/mlu/bridges/test_transpose_converter_mlu
    - name: test_slice_converter_mlu
      run: ./build.lite.mlu/lite/kernels/mlu/bridges/test_slice_converter_mlu
    - name: test_argmax_converter_mlu
      run: ./build.lite.mlu/lite/kernels/mlu/bridges/test_argmax_converter_mlu
    - name: test_split_converter_mlu
      run: ./build.lite.mlu/lite/kernels/mlu/bridges/test_split_converter_mlu
    - name: test_lrn_converter_mlu
      run: ./build.lite.mlu/lite/kernels/mlu/bridges/test_lrn_converter_mlu
    - name: test_gather_converter_mlu
      run: ./build.lite.mlu/lite/kernels/mlu/bridges/test_gather_converter_mlu
    - name: test_classification_resnet50
      run: |
        cd ..
        rm -rf Paddle-Lite-models
        git clone -b gtest git@github.com:Cambricon/Paddle-Lite-models.git
        cd Paddle-Lite-models
        sed -i 's/\/home\/dingminghui\/paddle/${PWD}\/../' prepare_paddle_env.sh
        cp /opt/share/datasets/imagenet/val_1000.txt classification/filelist
        sed -i 's/^/\/opt\/share\/datasets\/imagenet\//' classification/filelist
        ./prepare_paddle_env.sh 0
        cd classification 
        ./classification_demo --gtest_filter="classification_test.resnet50" &> log
        [ `awk  'BEGIN {min=65536} /detected.*subgraph/ {if($6<min) min=$6 fi} END {print min}' log` -eq 1 ]
        # [ `awk -v num=0 -v last=0 'BEGIN{} /average preprocess time/ {last=last*10+num; num=0} /START TO CONVERT/ {num++} END{print last}' log` -eq 171 ]
        [ `awk -v num=0 -v result=0 'BEGIN{} /compile_times/ {if($2!=num) result++; num=0 fi} /START TO CONVERT/ {num++} END{print result}' log` -eq 0 ]
    - name: test_classification_resnet50_without_batchsize_changeble
        cd /home/jiaopu/actions-runner/_work/Paddle-Lite/Paddle-Lite-models/classification
        PADDLE_LITE_MLU_DISABLE_BATCH_SIZE_CHANGEABLE=true ./classification_demo --gtest_filter="classification_test.resnet50" &> log
        [ `awk  'BEGIN {min=65536} /detected.*subgraph/ {if($6<min) min=$6 fi} END {print min}' log` -eq 1 ]
        # [ `awk -v num=0 -v last=0 'BEGIN{} /average preprocess time/ {last=last*10+num; num=0} /START TO CONVERT/ {num++} END{print last}' log` -eq 171 ]
        [ `awk -v num=0 -v result=0 'BEGIN{} /compile_times/ {if($2!=num) result++; num=0 fi} /START TO CONVERT/ {num++} END{print result}' log` -eq 0 ]
    - name: test_classification_resnet101
      run: |
        cd /home/jiaopu/actions-runner/_work/Paddle-Lite/Paddle-Lite-models/classification
        ./classification_demo --gtest_filter="classification_test.resnet101" &> log
        [ `awk  'BEGIN {min=65536} /detected.*subgraph/ {if($6<min) min=$6 fi} END {print min}' log` -eq 1 ]
        hardware_time=`awk '/hardware/ {print $7}' log` && [ `awk -v a=$hardware_time -v b=10 'BEGIN{print(a<b)?"0":"1"}'` -eq 0 ]
        [ `awk -v num=0 -v result=0 'BEGIN{} /compile_times/ {if($2!=num) result++; num=0 fi} /START TO CONVERT/ {num++} END{print result}' log` -eq 0 ]
    - name: test_classification_mobilenetv2
      run: |
        cd /home/jiaopu/actions-runner/_work/Paddle-Lite/Paddle-Lite-models/classification
        ./classification_demo --gtest_filter="classification_test.mobilenetv2_KL" &> log
        [ `awk  'BEGIN {min=65536} /detected.*subgraph/ {if($6<min) min=$6 fi} END {print min}' log` -eq 1 ]
        hardware_time=`awk '/hardware/ {print $7}' log` && [ `awk -v a=$hardware_time -v b=5 'BEGIN{print(a<b)?"0":"1"}'` -eq 0 ]
        [ `awk -v num=0 -v result=0 'BEGIN{} /compile_times/ {if($2!=num) result++; num=0 fi} /START TO CONVERT/ {num++} END{print result}' log` -eq 0 ]
    - name: test_classification_googlenet
      run: |
        cd /home/jiaopu/actions-runner/_work/Paddle-Lite/Paddle-Lite-models/classification
        ./classification_demo --gtest_filter="classification_test.googlenet_KL" &> log
        [ `awk  'BEGIN {min=65536} /detected.*subgraph/ {if($6<min) min=$6 fi} END {print min}' log` -eq 1 ]
        hardware_time=`awk '/hardware.*101/ {print $7}' log` && [ `awk -v a=$hardware_time -v b=4 'BEGIN{print(a<b)?"0":"1"}'` -eq 0 ]
        # tmp=`grep -o "START TO CONVERT" log | wc -l` && [ $tmp -eq 2 ]
        [ `awk -v num=0 -v result=0 'BEGIN{} /compile_times/ {if($2!=num) result++; num=0 fi} /START TO CONVERT/ {num++} /build batch_size changeable subgraph op failed/ {num--}END{print result}' log` -eq 0 ]
    - name: test_classification_MobileNet
      run: |
        cd /home/jiaopu/actions-runner/_work/Paddle-Lite/Paddle-Lite-models/classification
        ./classification_demo --gtest_filter="classification_test.MobileNetV1" &> log
        [ `awk  'BEGIN {min=65536} /detected.*subgraph/ {if($6<min) min=$6 fi} END {print min}' log` -eq 1 ]
        hardware_time=`awk '/hardware/ {print $7}' log` && [ `awk -v a=$hardware_time -v b=3.5 'BEGIN{print(a<b)?"0":"1"}'` -eq 0 ]
        [ `awk -v num=0 -v result=0 'BEGIN{} /compile_times/ {if($2!=num) result++; num=0 fi} /START TO CONVERT/ {num++} END{print result}' log` -eq 0 ]
    - name: test_classification_resnet50_extra
      run: |
        cd /home/jiaopu/actions-runner/_work/Paddle-Lite/Paddle-Lite-models/classification
        ./classification_demo --gtest_filter="classification_test.resnet50_extra" &> log
        [ `awk  'BEGIN {min=65536} /detected.*subgraph/ {if($6<min) min=$6 fi} END {print min}' log` -eq 1 ]
        hardware_time=`awk  'BEGIN {max=-1} /hardware/ {if($7>max) max=$7 fi} END {print max}' log` && [ `awk -v a=$hardware_time -v b=8 'BEGIN{print(a<b)?"0":"1"}'` -eq 0 ]
        [ `awk -v num=0 -v result=0 'BEGIN{} /compile_times/ {if($2!=num) result++; num=0 fi} /START TO CONVERT/ {num++} END{print result}' log` -eq 0 ]
