name: C/C++ CI

on:
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: NEUWARE_HOME=/usr/local/neuware ./lite/tools/build_mlu.sh build
